#1)WAQTD NAMES AND SALARIES OF EMPLOYEES ARRANGE THE RECORDS BASED ON THEIR NAMES IN AESCENDING AND SAL IN DESCENDING ORDER.
SELECT NAMES , SALARIES 
FROM EMPLOYEES
ORDER BY NAMES ASC , SALARIES DESC;

#2)WAQTD TOTAL NO. OF EMPLS WORKING IN EACH DEPT AND ORDER BY NO. OF EMPLS.
SELECT DEPTNO, COUNT(*) AS TOTAL_EMPLOYEES
FROM EMPLOYEES
GROUP BY DEPTNO
ORDER BY TOTAL_EMPLOYEES;

#3) WAQTD DETAILS OF EMPLS BASED ON THEIR JOBS AND SAL IN DESCENDING ORDER.
SELECT *
FROM EMPLOYEES
ORDER BY JOB, SAL DESC;

#4) WAQTD DETAILS OF EMPLS WHO ARE EARNING GREATER THAN MILLER.
SELECT *
FROM EMPLOYEES
WHERE SAL > (SELECT SAL FROM EMPLOYEES WHERE ENAME = 'MILLER');

#5) WAQTD WHO ARE WORKING AS SALESMAN IN THE SAME DEPT OF WARD.
SELECT *
FROM EMPLOYEES
WHERE JOB = 'SALESMAN'
AND DEPTNO = (SELECT DEPTNO FROM EMPLOYEES WHERE ENAME = 'WARD');

#6) WAQTD DETAILS OF EMPLS WHO ARE EARNING IN RANGE OF 1000 TO 3000 AND HIRED AFTER SMITH.
SELECT *
FROM EMPLOYEES
WHERE SAL BETWEEN 1000 AND 3000
AND HIREDATE > (SELECT HIREDATE FROM EMPLOYEES WHERE ENAME = 'SMITH');

#7) WAQTD NAME, HIREDATE OF EMPLS WHO ARE NOT EARNING COMM, EARNING SALARY GREATER THAN MILLER AND WORKING AS A SALESMAN, ANALYST, #PRESIDENT OR MANAGER.

SELECT ENAME, HIREDATE
FROM EMPLOYEES
WHERE COMM IS NULL
AND SAL > (SELECT SAL FROM EMPLOYEES WHERE ENAME = 'MILLER')
AND JOB IN ('SALESMAN', 'ANALYST', 'PRESIDENT', 'MANAGER');

#8) WAQTD DETAILS OF EMPLS WHO ARE EARNING SALARY MORE THAN SMITH AND LESS THAN SCOTT BUT HIRED AFTER ALLEN AND BEFORE ADAMS.

SELECT *
FROM EMPLOYEES
WHERE SAL > (SELECT SAL FROM EMPLOYEES WHERE ENAME = 'SMITH')
AND SAL < (SELECT SAL FROM EMPLOYEES WHERE ENAME = 'SCOTT')
AND HIREDATE > (SELECT HIREDATE FROM EMPLOYEES WHERE ENAME = 'ALLEN')
AND HIREDATE < (SELECT HIREDATE FROM EMPLOYEES WHERE ENAME = 'ADAMS');


#9) WAQTD EMPNO, ENAME ALONG WITH ANNUAL_SAL OF ALL EMPLS IF THEIR ANNUAL_SAL IS GREATER THAN WARDS ANNUAL_SAL.

SELECT EMPNO, ENAME, SAL*12 AS ANNUAL_SAL
FROM EMPLOYEES
WHERE SAL*12 > (SELECT SAL*12 FROM EMPLOYEES WHERE ENAME = 'WARD');

#10) WAQTD NAMES ALONG WITH SALARIES OF EMPLS WHOSE SAL IS GREATER THAN MILLER AND WORKING IN LOCATION NEW YORK.

SELECT E.ENAME, E.SAL
FROM EMPLOYEES E
JOIN DEPT D ON E.DEPTNO = D.DEPTNO
WHERE E.SAL > (SELECT SAL FROM EMPLOYEES WHERE ENAME = 'MILLER')
AND D.LOC = 'NEW YORK';

#11) WAQTD DETAILS OF EMPLS WHO ARE HIRED AFTER ALLEN IN DEPT RESEARCH.

SELECT *
FROM EMPLOYEES E
JOIN DEPT D ON E.DEPTNO = D.DEPTNO
WHERE D.DNAME = 'RESEARCH'
AND E.HIREDATE > (SELECT HIREDATE FROM EMPLOYEES WHERE ENAME = 'ALLEN');

#12) WAQTD DNAME OF EMP IN WHICH SMITH IS WORKING.
SELECT D.DNAME
FROM DEPT D
JOIN EMPLOYEES E ON D.DEPTNO = E.DEPTNO
WHERE E.ENAME = 'SMITH';

#13) WAQTD DNAME, LOCATION ALONG WITH DEPTNO OF EMP WHOSE NAME ENDS WITH ‘R’.
SELECT D.DNAME, D.LOC, D.DEPTNO
FROM DEPT D
JOIN EMPLOYEES E ON D.DEPTNO = E.DEPTNO
WHERE E.ENAME LIKE '%R';


#14) WAQTD NAMES OF EMPLS WHO IS EARNING MAXIMUM SALARY.
SELECT ENAME
FROM EMPLOYEES
WHERE SAL = (SELECT MAX(SAL) FROM EMPLOYEES);

#15) WAQTD NAMES, SALARIES AND COMMISSION OF EMPLS WHO ARE EARNING MINIMUM COMMISSION.

SELECT ENAME, SAL, COMM
FROM EMPLOYEES
WHERE COMM = (SELECT MIN(COMM) FROM EMPLOYEES WHERE COMM IS NOT NULL);

#16) WAQTD DETAILS OF EMPLS WHOSE DNAME CONTAINS CHARACTER ‘A’.

SELECT E.*
FROM EMPLOYEES E
JOIN DEPT D ON E.DEPTNO = D.DEPTNO
WHERE D.DNAME LIKE '%A%';
